# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.


arr = [1]

x1 = 1
x2 = 1
sum = 0
evensum = 0

while arr.max <= 4000000 do
  sum = x1 + x2
  arr << sum
  x1 = x2
  x2 = sum
  sum = 0
end

arr.each do |x|
  if x.even? == true
    evensum += x
  end
end

arr.delete_at(-1)

puts "Fibonacci array #{arr}"
puts "Max item = #{arr.max}"
puts "Array have #{arr.length} numbers"
puts "Sum all even numbers = #{evensum}"